"""Initial migration

Revision ID: 14b3d74b9ef4
Revises: 
Create Date: 2026-01-27 19:39:41.639207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14b3d74b9ef4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Keeping changes for modeled tables
    op.alter_column('email_queue', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('email_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('initial_passwords', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('initial_passwords', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    
    # Adjusting indexes for Students
    op.drop_index('idx_students_class', table_name='students')
    op.drop_index('idx_students_code', table_name='students')
    op.drop_constraint('students_student_code_key', 'students', type_='unique')
    op.create_index(op.f('ix_students_student_code'), 'students', ['student_code'], unique=True)
    
    # Adjusting Users
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_role', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_students_student_code'), table_name='students')
    op.create_unique_constraint('students_student_code_key', 'students', ['student_code'])
    op.create_index('idx_students_code', 'students', ['student_code'], unique=False)
    op.create_index('idx_students_class', 'students', ['class_name'], unique=False)
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('initial_passwords', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('initial_passwords', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('email_queue', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('email_queue', 'sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases')
    op.drop_table('enrollments')
    op.drop_index(op.f('idx_plagiarism_review_status'), table_name='plagiarism_checks')
    op.drop_index(op.f('idx_plagiarism_submission'), table_name='plagiarism_checks')
    op.drop_index(op.f('idx_plagiarism_suspicious'), table_name='plagiarism_checks')
    op.drop_table('plagiarism_checks')
    op.drop_table('code_fingerprints')
    op.drop_table('classes')
    op.drop_table('student_import_batches')
    op.drop_table('ai_hint_usage')
    op.drop_table('notifications')
    op.drop_table('courses')
    op.drop_table('ai_hint_configs')
    op.drop_index(op.f('idx_assignments_class'), table_name='assignments')
    op.drop_index(op.f('idx_assignments_due_date'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('submission_test_results')
    op.drop_index(op.f('idx_submissions_assignment'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_status'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_student'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_submitted_at'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('idx_problems_course'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('idx_ai_hints_created'), table_name='ai_hints')
    op.drop_index(op.f('idx_ai_hints_student_assignment'), table_name='ai_hints')
    op.drop_table('ai_hints')
    op.alter_column('email_queue', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('email_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('initial_passwords', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('initial_passwords', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.drop_index(op.f('idx_students_class'), table_name='students')
    op.drop_index(op.f('idx_students_code'), table_name='students')
    op.drop_constraint(op.f('students_student_code_key'), 'students', type_='unique')
    op.create_index(op.f('ix_students_student_code'), 'students', ['student_code'], unique=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_students_student_code'), table_name='students')
    op.create_unique_constraint(op.f('students_student_code_key'), 'students', ['student_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_students_code'), 'students', ['student_code'], unique=False)
    op.create_index(op.f('idx_students_class'), 'students', ['class_name'], unique=False)
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('initial_passwords', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('initial_passwords', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('email_queue', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('email_queue', 'sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('ai_hints',
    sa.Column('hint_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('student_question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('student_code_snapshot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hint_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ai_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name=op.f('ai_hints_assignment_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('ai_hints_student_id_fkey')),
    sa.PrimaryKeyConstraint('hint_id', name=op.f('ai_hints_pkey'))
    )
    op.create_index(op.f('idx_ai_hints_student_assignment'), 'ai_hints', ['student_id', 'assignment_id'], unique=False)
    op.create_index(op.f('idx_ai_hints_created'), 'ai_hints', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('problems',
    sa.Column('problem_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('problem_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('time_limit', sa.INTEGER(), server_default=sa.text('1000'), autoincrement=False, nullable=True),
    sa.Column('memory_limit', sa.INTEGER(), server_default=sa.text('256'), autoincrement=False, nullable=True),
    sa.Column('allowed_languages', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('problems_course_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('problems_created_by_fkey')),
    sa.PrimaryKeyConstraint('problem_id', name=op.f('problems_pkey')),
    sa.UniqueConstraint('problem_code', name=op.f('problems_problem_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_problems_course'), 'problems', ['course_id'], unique=False)
    op.create_table('submissions',
    sa.Column('submission_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('execution_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_cases_passed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_test_cases', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_late', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('judged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name=op.f('submissions_assignment_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('submissions_student_id_fkey')),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('submissions_pkey'))
    )
    op.create_index(op.f('idx_submissions_submitted_at'), 'submissions', [sa.literal_column('submitted_at DESC')], unique=False)
    op.create_index(op.f('idx_submissions_student'), 'submissions', ['student_id'], unique=False)
    op.create_index(op.f('idx_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('idx_submissions_assignment'), 'submissions', ['assignment_id'], unique=False)
    op.create_table('submission_test_results',
    sa.Column('result_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('test_case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('execution_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name=op.f('submission_test_results_submission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.test_case_id'], name=op.f('submission_test_results_test_case_id_fkey')),
    sa.PrimaryKeyConstraint('result_id', name=op.f('submission_test_results_pkey'))
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('problem_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('max_score', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('100'), autoincrement=False, nullable=True),
    sa.Column('allow_late_submission', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('late_penalty_percent', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('10'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name=op.f('assignments_class_id_fkey')),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], name=op.f('assignments_problem_id_fkey')),
    sa.PrimaryKeyConstraint('assignment_id', name=op.f('assignments_pkey'))
    )
    op.create_index(op.f('idx_assignments_due_date'), 'assignments', ['due_date'], unique=False)
    op.create_index(op.f('idx_assignments_class'), 'assignments', ['class_id'], unique=False)
    op.create_table('ai_hint_configs',
    sa.Column('config_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('max_hints_per_student', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('hint_cooldown_minutes', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True),
    sa.Column('allow_code_hints', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('allow_algorithm_hints', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name=op.f('ai_hint_configs_assignment_id_fkey')),
    sa.PrimaryKeyConstraint('config_id', name=op.f('ai_hint_configs_pkey'))
    )
    op.create_table('courses',
    sa.Column('course_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('programming_languages', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('course_id', name=op.f('courses_pkey')),
    sa.UniqueConstraint('course_code', name=op.f('courses_course_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('notifications_pkey'))
    )
    op.create_table('ai_hint_usage',
    sa.Column('usage_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('hints_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_hint_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name=op.f('ai_hint_usage_assignment_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('ai_hint_usage_student_id_fkey')),
    sa.PrimaryKeyConstraint('usage_id', name=op.f('ai_hint_usage_pkey')),
    sa.UniqueConstraint('student_id', 'assignment_id', name=op.f('ai_hint_usage_student_id_assignment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('student_import_batches',
    sa.Column('batch_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('lecturer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('total_records', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('successful_imports', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('failed_imports', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'processing'::character varying"), autoincrement=False, nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.lecturer_id'], name=op.f('student_import_batches_lecturer_id_fkey')),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('student_import_batches_pkey'))
    )
    op.create_table('classes',
    sa.Column('class_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('class_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('lecturer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('semester', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('classes_course_id_fkey')),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.lecturer_id'], name=op.f('classes_lecturer_id_fkey')),
    sa.PrimaryKeyConstraint('class_id', name=op.f('classes_pkey')),
    sa.UniqueConstraint('class_code', name=op.f('classes_class_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('code_fingerprints',
    sa.Column('fingerprint_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('problem_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('structure_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('variable_pattern', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logic_signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], name=op.f('code_fingerprints_problem_id_fkey')),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name=op.f('code_fingerprints_submission_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fingerprint_id', name=op.f('code_fingerprints_pkey'))
    )
    op.create_table('plagiarism_checks',
    sa.Column('check_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ai_generated_probability', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_suspicious', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('detection_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('analysis_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('flagged_sections', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('similar_submissions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('review_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], name=op.f('plagiarism_checks_reviewed_by_fkey')),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name=op.f('plagiarism_checks_submission_id_fkey')),
    sa.PrimaryKeyConstraint('check_id', name=op.f('plagiarism_checks_pkey'))
    )
    op.create_index(op.f('idx_plagiarism_suspicious'), 'plagiarism_checks', ['is_suspicious'], unique=False)
    op.create_index(op.f('idx_plagiarism_submission'), 'plagiarism_checks', ['submission_id'], unique=False)
    op.create_index(op.f('idx_plagiarism_review_status'), 'plagiarism_checks', ['review_status'], unique=False)
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name=op.f('enrollments_class_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('enrollments_student_id_fkey')),
    sa.PrimaryKeyConstraint('enrollment_id', name=op.f('enrollments_pkey')),
    sa.UniqueConstraint('class_id', 'student_id', name=op.f('enrollments_class_id_student_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('test_cases',
    sa.Column('test_case_id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), autoincrement=False, nullable=False),
    sa.Column('problem_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('input', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expected_output', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_sample', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('points', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('10'), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.problem_id'], name=op.f('test_cases_problem_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_case_id', name=op.f('test_cases_pkey'))
    )
    # ### end Alembic commands ###
