"""create_menus_table

Revision ID: fe93ca7d13ac
Revises: 14b3d74b9ef4
Create Date: 2026-01-27 20:26:43.806650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe93ca7d13ac'
down_revision: Union[str, Sequence[str], None] = '14b3d74b9ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.menu_id'], ),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_menus_menu_id'), 'menus', ['menu_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_menu_id'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
